#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XN_ListView.Droid.Resource", IsApplication=true)]

namespace XN_ListView.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monkey1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monkey2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monkey3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monkey4 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int AddButton = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int CustomListView = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int RemoveButton = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int imageView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int mainText = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int subText = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
